// Regenerates src/gamedata.ts from an installed copy of the game.
//
//   deno run -R -W --allow-run tools/gamedata.ts "<game dir>" "<dir with sprites.json from dump_meta.csx>"
//
// Only short factual labels and sprite bounding boxes are copied; no game art or code.

const [gameDir, metaDir] = Deno.args;
if (!gameDir || !metaDir) {
  console.error('usage: deno run -R -W tools/gamedata.ts "<game dir>" "<meta dir>"');
  Deno.exit(2);
}

function readIni(path: string): Map<string, Map<string, string>> {
  const sections = new Map<string, Map<string, string>>();
  let cur = new Map<string, string>();
  for (const raw of Deno.readTextFileSync(path).split(/\r?\n/)) {
    const line = raw.trim();
    const sec = /^\[(.+)\]$/.exec(line);
    if (sec) {
      cur = sections.get(sec[1]) ?? new Map();
      sections.set(sec[1], cur);
      continue;
    }
    const kv = /^([^=]+)=(.*)$/.exec(line);
    if (kv) cur.set(kv[1].trim(), kv[2].trim().replace(/^"(.*)"$/, "$1"));
  }
  return sections;
}

function numbered(section: Map<string, string> | undefined): Record<number, string> {
  const out: Record<number, string> = {};
  for (const [k, v] of section ?? []) if (/^-?\d+$/.test(k)) out[Number(k)] = v;
  return out;
}

const lang = `${gameDir}/Languages/English`;
const ui = readIni(`${lang}/UI.ini`);
const bestiary = readIni(`${lang}/Bestiary.ini`);
const nature = readIni(`${lang}/Nature.ini`);
const items = readIni(`${lang}/Items.ini`);

type Sprite = { name: string; w: number; h: number; ox: number; oy: number; bl: number; br: number; bt: number; bb: number };
const sprites: Sprite[] = JSON.parse(Deno.readTextFileSync(`${metaDir}/sprites.json`));
const keep =
  /^spr_(boulders|ruins|caves|cavesolids|entrances|building|built|found|placed|rift|stairs|drops|part_circles|soldier)|^spr_(human_legs|male1|ui_frame_16)$/;
const spriteTable: Record<string, number[]> = {};
for (const s of sprites.filter((s) => keep.test(s.name)).sort((a, b) => a.name.localeCompare(b.name))) {
  spriteTable[s.name] = [s.w, s.h, s.ox, s.oy, s.bl, s.br, s.bt, s.bb];
}

const table = (o: Record<string | number, unknown>) =>
  "{\n" + Object.entries(o).map(([k, v]) => `  ${/^\d+$/.test(k) ? k : JSON.stringify(k)}: ${JSON.stringify(v)},`).join("\n") + "\n}";

const out = `// Generated by tools/gamedata.ts from Mirklurk's English language files and sprite metadata.
// Do not edit by hand; rerun the tool after a game update.

/** [LocTitles] in UI.ini: zone names keyed by area type. */
export const ZONE_NAMES: Record<number, string> = ${table(numbered(ui.get("LocTitles")))};

/** [Titles] in Bestiary.ini: being names keyed by being index. */
export const BEING_NAMES: Record<number, string> = ${table(numbered(bestiary.get("Titles")))};

/** [MapLocation] in Bestiary.ini: labels the game prints on its own area maps. */
export const MAP_LABELS: Record<number, string> = ${table(numbered(bestiary.get("MapLocation")))};

/** [Titles] in Nature.ini: plant and tree names keyed by nature index. */
export const NATURE_NAMES: Record<number, string> = ${table(numbered(nature.get("Titles")))};

/** [ItemTitles] in Items.ini: item names keyed by item index (placed stations use these). */
export const ITEM_NAMES: Record<number, string> = ${table(numbered(items.get("ItemTitles")))};

/** Sprite geometry: [width, height, originX, originY, bboxLeft, bboxRight, bboxTop, bboxBottom]. */
export const SPRITES: Record<string, readonly number[]> = ${table(spriteTable)};
`;

const target = new URL("../src/gamedata.ts", import.meta.url);
Deno.writeTextFileSync(target, out);
const path = decodeURIComponent(target.pathname).replace(/^\/([A-Za-z]:)/, "$1");
await new Deno.Command(Deno.execPath(), { args: ["fmt", "--quiet", path] }).output();
console.log(`src/gamedata.ts: ${Object.keys(spriteTable).length} sprites`);
